### ISSUE TITLE
Unable to find the exercise folder

### ISSUE THREAD

**Issue by abhi-vardhan** [LinkedInLearning/learning-nextjs--codespaces--5914444#2]
## Issue Overview

I am unable to find the exercise folder where all the exercise files are present
![image](https://github.com/user-attachments/assets/93951dbd-d613-4a47-b37e-a09ad937f1a7)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by peterdavidhamilton** [comment]
@abhi-vardhan you need to `checkout` a `branch` first. There are two for each exercise, versions `b` and `e`.
![image](https://github.com/user-attachments/assets/77c9ac89-de9b-42b2-af18-b8249af127da)
